import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { SCIM_BASE } from '../server/scim.js';

/**
 * The published spec, against the routes that actually exist.
 *
 * Adopted from PS-12, which learned it the expensive way: nothing checked
 * `openapi.yaml` at all, so the file could be broken outright — an
 * unterminated quoted string — with the whole suite still green.
 *
 * PS-01 needs it for a second reason PS-12 does not have. This service now
 * registers routes in TWO files: the API in `app.ts` and the SCIM surface in
 * `scim.ts`, mounted under a prefix. A spec generated by reading one of them
 * is wrong about the other, and the way that goes wrong is silent — an IdP
 * connector built from the document finds a 404 where the document promised an
 * endpoint.
 */

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const app = readFileSync(join(ROOT, 'server/app.ts'), 'utf8');
const scim = readFileSync(join(ROOT, 'server/scim.ts'), 'utf8');
const spec = readFileSync(join(ROOT, 'openapi.yaml'), 'utf8');

type Route = `${string} ${string}`;

/** What the two route files register, with `:param` written the spec's way. */
function registeredRoutes(): Set<Route> {
  const found = new Set<Route>();
  const collect = (source: string, pattern: RegExp, prefix = ''): void => {
    for (const match of source.matchAll(pattern)) {
      const path = match[2]!.replace(/:([A-Za-z_][A-Za-z0-9_]*)/g, '{$1}');
      found.add(`${match[1]!} ${prefix}${path}`);
    }
  };
  collect(app, /app\.(get|post|put|patch|delete)\(\s*'([^']+)'/g);
  collect(scim, /router\.(get|post|put|patch|delete)\(\s*'([^']+)'/g, SCIM_BASE);
  return found;
}

/** What the spec documents, as method/path pairs. */
function documentedRoutes(): Set<Route> {
  const found = new Set<Route>();
  let path: string | null = null;
  for (const line of spec.split('\n')) {
    const pathLine = /^ {2}(\/\S*):\s*$/.exec(line);
    if (pathLine) {
      path = pathLine[1]!;
      continue;
    }
    const verb = /^ {4}(get|post|put|patch|delete):\s*$/.exec(line);
    if (verb && path !== null) found.add(`${verb[1]!} ${path}`);
  }
  return found;
}

describe('openapi.yaml', () => {
  it('is well-formed enough to read — every quoted scalar is closed', () => {
    const unbalanced: string[] = [];
    spec.split('\n').forEach((line, index) => {
      const scalar = /^\s*[A-Za-z_][\w-]*:\s+'(.*)$/.exec(line);
      if (scalar && !scalar[1]!.endsWith("'")) unbalanced.push(`${index + 1}: ${line.trim()}`);
    });
    expect(unbalanced).toEqual([]);
  });

  it('finds routes on both sides, so a broken parser cannot pass silently', () => {
    expect(registeredRoutes().size).toBeGreaterThan(20);
    expect(documentedRoutes().size).toBeGreaterThan(20);
  });

  it('covers the SCIM surface, which lives in its own file behind a prefix', () => {
    const scimRoutes = [...registeredRoutes()].filter((r) => r.includes(SCIM_BASE));
    expect(scimRoutes.length).toBeGreaterThan(8);
    expect(scimRoutes).toContain(`delete ${SCIM_BASE}/Users/{id}`);
  });

  it('documents every route the service registers', () => {
    const undocumented = [...registeredRoutes()].filter((r) => !documentedRoutes().has(r)).sort();
    expect(undocumented).toEqual([]);
  });

  it('registers every route the spec documents', () => {
    const phantom = [...documentedRoutes()].filter((r) => !registeredRoutes().has(r)).sort();
    expect(phantom).toEqual([]);
  });
});
