#!/bin/sh
# Nightly backups for ONE stack: every running container that ships a backup
# script snapshots its own database (and any files beside it) onto its volume.
#
#   ./backup.sh                     # the reference stack in this directory
#   ./backup.sh /opt/customers/xy   # a stack generated by provision.mjs
#
# Schedule it from the host's cron, e.g.
#   0 2 * * *  /opt/platform/deploy/backup.sh /opt/customers/xy >> backup.log 2>&1
#
# The containers are asked which ones exist rather than being listed here: a
# generated stack holds only the services its module selection needs, plus one
# container per module, and a hardcoded list silently skips whatever it forgot
# — which is exactly how PS-11 and all fourteen modules went unbacked-up.
#
# IMPORTANT: each snapshot lands on that container's own volume. That survives a
# bad deploy, not a lost disk. Copy the snapshots off the host afterwards
# (rsync/restic to another machine); that is the step that makes this a backup
# rather than a convenience. Back up the stack's .env separately — a restored
# volume is useless with the wrong SESSION_SECRET.
set -eu

STACK_DIR="${1:-$(dirname "$0")}"
cd "$STACK_DIR"

failed=''
backed_up=''

for svc in $(docker compose ps --services --status running); do
  # Caddy and the ticker hold no data and ship no backup script.
  if ! docker compose exec -T "$svc" node -e 'process.exit(require("fs").existsSync("scripts/backup.mjs") ? 0 : 1)' 2>/dev/null; then
    continue
  fi
  echo "[backup] $svc"
  if docker compose exec -T "$svc" npm run --silent backup; then
    backed_up="$backed_up $svc"
  else
    echo "[backup] FAILED: $svc" >&2
    failed="$failed $svc"
  fi
done

if [ -z "$backed_up" ]; then
  echo "[backup] nothing was backed up — is the stack running?" >&2
  exit 1
fi

echo "[backup] done $(date -u +%FT%TZ):$backed_up"
if [ -n "$failed" ]; then
  echo "[backup] INCOMPLETE — failed:$failed" >&2
  exit 1
fi
